
#ifdef VENDOR_EDIT
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_s3508/
#add for hall sensor
obj-$(CONFIG_HALL) += hall/
#add for pswtich sensor
obj-$(CONFIG_PSWITCH) += hall/
#add for dhall sensor
obj-$(CONFIG_DHALL_M1120) += hall/
#add for uei 
obj-$(CONFIG_UEI) += uei/
#endif
