#
# Makefile for nfc devices

# 15 Oct 2013, Yuyi <oppo@Independent Group>
# Rewritten to use pn544 driver.

obj-$(CONFIG_PN544_NFC)		+= pn547.o

#obj-$(CONFIG_NFC_PN533)		+= pn533.o
#obj-$(CONFIG_NFC_WILINK)	+= nfcwilink.o

#ccflags-$(CONFIG_NFC_DEBUG) := -DDEBUG
