#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_oppo_driver.o synaptics_oppo_driver_14045_17tp.o
obj-$(CONFIG_SYNAPTICS_OPPO) += synaptics_redremote.o
#endif